spring:
  datasource:
    url: jdbc:mysql://fourtysixhundred.cqfyoejixbll.ap-northeast-2.rds.amazonaws.com:3306/fivesix_hundred
    username: admin
    password: Tndi84072#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: 46WEB-POOL
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  data:    rest:      base-path: api